
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ETAG OTAG TAG_TEXTcheck : OTAG TAG_TEXT ETAG'
    
_lr_action_items = {'OTAG':([0,],[2,]),'$end':([1,4,],[0,-1,]),'TAG_TEXT':([2,],[3,]),'ETAG':([3,],[4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'check':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> check","S'",1,None,None,None),
  ('check -> OTAG TAG_TEXT ETAG','check',3,'p_check','img_tag.py',23),
]
